webtalk_init -webtalk_dir E:\\class\\Project\\project_2\\project_2.sdk\\webtalk
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "星期二 四月 14 21:39:01 2015" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "SDK v2014.2" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2014.2" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "amd64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "SDK" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "false" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "ocviing9taqersjr9a20j7knl0" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "2014.2_11" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "11" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 7 , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Service Pack 1  (build 7601)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "AMD A6-3430MX APU with Radeon(tm) HD Graphics" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "1696 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "5.000 GB" -context "user_environment"
webtalk_register_client -client sdk
webtalk_add_data -client sdk -key uid -value "1429015791362" -context "sdk\\\\bsp/1429015791362"
webtalk_add_data -client sdk -key hwid -value "1427169368194" -context "sdk\\\\bsp/1429015791362"
webtalk_add_data -client sdk -key os -value "standalone" -context "sdk\\\\bsp/1429015791362"
webtalk_add_data -client sdk -key apptemplate -value "null" -context "sdk\\\\bsp/1429015791362"
webtalk_add_data -client sdk -key uid -value "1429018270230" -context "sdk\\\\bsp/1429018270230"
webtalk_add_data -client sdk -key hwid -value "1428988147933" -context "sdk\\\\bsp/1429018270230"
webtalk_add_data -client sdk -key os -value "standalone" -context "sdk\\\\bsp/1429018270230"
webtalk_add_data -client sdk -key apptemplate -value "null" -context "sdk\\\\bsp/1429018270230"
webtalk_add_data -client sdk -key uid -value "1429018325933" -context "sdk\\\\application/1429018325933"
webtalk_add_data -client sdk -key hwid -value "1428988147933" -context "sdk\\\\application/1429018325933"
webtalk_add_data -client sdk -key bspid -value "1429018270230" -context "sdk\\\\application/1429018325933"
webtalk_add_data -client sdk -key newbsp -value "false" -context "sdk\\\\application/1429018325933"
webtalk_add_data -client sdk -key os -value "standalone" -context "sdk\\\\application/1429018325933"
webtalk_add_data -client sdk -key apptemplate -value "empty_application" -context "sdk\\\\application/1429018325933"
webtalk_transmit -clientid 1859723260 -regid "" -xml E:\\class\\Project\\project_2\\project_2.sdk\\webtalk\\usage_statistics_ext_sdk.xml -html E:\\class\\Project\\project_2\\project_2.sdk\\webtalk\\usage_statistics_ext_sdk.html -wdm E:\\class\\Project\\project_2\\project_2.sdk\\webtalk\\sdk.wdm -intro "<H3>SDK Usage Report</H3><BR>"
webtalk_terminate
